- name: add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: install docker
  yum:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: enable and start docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: install docker-compose 
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
    dest: /usr/local/sbin/docker-compose
    mode: 'u+x,g+x'

